### PR TITLE
add new test cases for error handlers in READ and CREATE api

### PR DESCRIPTION
**Pull request by yf1357**
Add test cases for error handlers
image

Check pep8 compliance
image

### CODE REVIEW

**Comment by abhinavGupta16** [comment]
The response does give a 404, but as an HTML response. We are to only return json responses. If you test for the error message, the test case will fail.

Irrespectively, the test case should include the expected error message in response to the error.

However, that would require merging #23 I believe

**Review by abhinavGupta16 — CHANGES_REQUESTED** [review]
**Added from previous PR**

The response does give a 404, but as an HTML response. We are to only return json responses. If you test for the error message, the test case will fail.

Irrespectively, the test case should include the expected error message in response to the error.

However, that would require merging #23 I believe

**Comment by yf1357** [comment]
> **Added from previous PR**
> 
> The response does give a 404, but as an HTML response. We are to only return json responses. If you test for the error message, the test case will fail.
> 
> Irrespectively, the test case should include the expected error message in response to the error.
> 
> However, that would require merging #23 I believe

I test it with request_validation_error(error) and bad_request() functions in issue# 27, and it passes the test case. I just find issue#27 is not merged, I should wait for it.

**Comment by sqz0914** [comment]
> > **Added from previous PR**
> > The response does give a 404, but as an HTML response. We are to only return json responses. If you test for the error message, the test case will fail.
> > Irrespectively, the test case should include the expected error message in response to the error.
> > However, that would require merging #23 I believe
> 
> I test it with request_validation_error(error) and bad_request() functions in issue# 27, and it passes the test case. I just find issue#27 is not merged, I should wait for it.

Yeah. Let's wait for the successful merge of #23 and then review this PR. I apologize for the confusion about my approval.

**Comment by abhinavGupta16** [comment]
> > > **Added from previous PR**
> > > The response does give a 404, but as an HTML response. We are to only return json responses. If you test for the error message, the test case will fail.
> > > Irrespectively, the test case should include the expected error message in response to the error.
> > > However, that would require merging #23 I believe
> > 
> > 
> > I test it with request_validation_error(error) and bad_request() functions in issue# 27, and it passes the test case. I just find issue#27 is not merged, I should wait for it.
> 
> Yeah. Let's wait for the successful merge of #23 and then review this PR. I apologize for the confusion about my approval.

Yeah. Once that is done, we can check for the response message in the test cases.

**Review by sqz0914 — DISMISSED** [review]
The tests run successfully. No problem with the expected error status code. The coverage is 97%.
Screen Shot 2020-10-16 at 6 52 35 PM

**Comment by abhinavGupta16** [comment]
@yf1357 - Looks good. We can also add the error message check for test_get_wishlist_not_found()

**Review by abhinavGupta16 — APPROVED** [review]

**Review by sqz0914 — APPROVED** [review]

**Pull request merged**
