### PR TITLE
update DELETE button to clear search results after deleting a wishlist

### PR DESCRIPTION
**Pull request by sqz0914**
1. update DELETE button to clear search results after deleting a wishlist
Screen Shot 2020-11-16 at 11 11 20 AM

### CODE REVIEW

**Review by abhinavGupta16 — APPROVED** [review]

**Comment by abhinavGupta16** [comment]
Tested on ibm cloud, it works fine now

**Comment by sqz0914** [comment]
> Tested on ibm cloud, it works fine now

Great! Somehow it needs to clean the search result after do delete. lol.

**Review by yf1357 — APPROVED** [review]

**Comment by abhinavGupta16** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b7dd79b7-17cc-412e-98f1-e1a234aafd1c?env_id=ibm:yp:us-south "nyu-wishlist-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/76e35b85-cc07-4faf-b3ae-ee3dbe88d89f "nyu-wishlist-service-f20-pipeline") deployed [wishlists](https://github.com/wishlists/wishlists/releases/tag/deploy-ibm-yp-us-south-ag7387-nyu.edu-prod-20201117-062944 "deploy-ibm-yp-us-south-ag7387-nyu.edu-prod-20201117-062944") to [prod](https://console.bluemix.net/apps/b9e11a39-3222-4ca4-a89b-8f6a16a809d0?env_id=ibm:yp:us-south "ibm:yp:us-south:ag7387@nyu.edu:prod"), including commit e2acfcc06881b9bd4c2dff277251edef04e87ee9

**Comment by abhinavGupta16** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b7dd79b7-17cc-412e-98f1-e1a234aafd1c?env_id=ibm:yp:us-south "nyu-wishlist-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/76e35b85-cc07-4faf-b3ae-ee3dbe88d89f "nyu-wishlist-service-f20-pipeline") deployed [wishlists](https://github.com/wishlists/wishlists/releases/tag/deploy-ibm-yp-us-south-ag7387-nyu.edu-dev-20201118-045327 "deploy-ibm-yp-us-south-ag7387-nyu.edu-dev-20201118-045327") to [dev](https://console.bluemix.net/apps/87d9b0cd-cdb0-4349-b181-099124ba4b73?env_id=ibm:yp:us-south "ibm:yp:us-south:ag7387@nyu.edu:dev"), including commit e2acfcc06881b9bd4c2dff277251edef04e87ee9

**Pull request merged**
