### PR TITLE
Refactor /wishlists/<int:wishlist_id>/items/<int:item_id>

### PR DESCRIPTION
**Pull request by Jesse1204**
There were some unexpected errors when I finished refactoring the URL for item id. 
image
Some unrelated tests failed. For example, when it tries to add an item to a wishlist, it calls route (/wishlists/<int:wishlist_id>/items/<int:item_id>), which is not supposed to do so. I think it is maybe related to the two-parameter setting.
image

image
Any thoughts on this issue?

### CODE REVIEW

**Comment by abhinavGupta16** [comment]
> There were some unexpected errors when I finished refactoring the URL for item id.
> image
> Some unrelated tests failed. For example, when it tries to add an item to a wishlist, it calls route (/wishlists/int:wishlist_id/items/int:item_id), which is not supposed to do so. I think it is maybe related to the two-parameter setting.
> image
> 
> image
> Any thoughts on this issue?

I believe the create item fails which fails all the other test cases. I agree it seems to be due to the parameters in the URL. You might want to check how other teams have handled 2 parameters.

**Comment by Jesse1204** [comment]
image
Fixed the bugs and it looks good now
image

**Review by sqz0914 — APPROVED** [review]

**Review by xiafanzeng — APPROVED** [review]

**Comment by abhinavGupta16** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b7dd79b7-17cc-412e-98f1-e1a234aafd1c?env_id=ibm:yp:us-south "nyu-wishlist-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/76e35b85-cc07-4faf-b3ae-ee3dbe88d89f "nyu-wishlist-service-f20-pipeline") deployed [wishlists](https://github.com/wishlists/wishlists/releases/tag/deploy-ibm-yp-us-south-ag7387-nyu.edu-dev-20201206-014934 "deploy-ibm-yp-us-south-ag7387-nyu.edu-dev-20201206-014934") to [dev](https://console.bluemix.net/apps/87d9b0cd-cdb0-4349-b181-099124ba4b73?env_id=ibm:yp:us-south "ibm:yp:us-south:ag7387@nyu.edu:dev"), including commit c9c5a6c77d11bfec5c7d36f14f9ffb8ba9c4f6c5

**Comment by abhinavGupta16** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b7dd79b7-17cc-412e-98f1-e1a234aafd1c?env_id=ibm:yp:us-south "nyu-wishlist-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/76e35b85-cc07-4faf-b3ae-ee3dbe88d89f "nyu-wishlist-service-f20-pipeline") deployed [wishlists](https://github.com/wishlists/wishlists/releases/tag/deploy-ibm-yp-us-south-ag7387-nyu.edu-prod-20201206-020212 "deploy-ibm-yp-us-south-ag7387-nyu.edu-prod-20201206-020212") to [prod](https://console.bluemix.net/apps/b9e11a39-3222-4ca4-a89b-8f6a16a809d0?env_id=ibm:yp:us-south "ibm:yp:us-south:ag7387@nyu.edu:prod"), including commit c9c5a6c77d11bfec5c7d36f14f9ffb8ba9c4f6c5

**Pull request merged**
