### PR TITLE
added update action to the update button

### PR DESCRIPTION
**Pull request by abhinavGupta16**

### CODE REVIEW

**Review by yf1357 — DISMISSED** [review]

**Comment by abhinavGupta16** [comment]
@sqz0914  -
Can you elaborate on this change? I am not sure I understand. == would just return a boolean right?

**Comment by sqz0914** [comment]
> @sqz0914 -
> Can you elaborate on this change? I am not sure I understand. == would just return a boolean right?


somehow when I access the UI after running behave, I cannot enable the electronics wishlist again before I make this change. But I will do some checks now. This change also makes no sense to me. Sorry for the confusion.

**Comment by sqz0914** [comment]
> @sqz0914 -
> Can you elaborate on this change? I am not sure I understand. == would just return a boolean right?

I just revert my change. My bad. I try again and it works. I am sorry.

**Review by sqz0914 — APPROVED** [review]

**Review by yf1357 — APPROVED** [review]

**Comment by abhinavGupta16** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b7dd79b7-17cc-412e-98f1-e1a234aafd1c?env_id=ibm:yp:us-south "nyu-wishlist-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/76e35b85-cc07-4faf-b3ae-ee3dbe88d89f "nyu-wishlist-service-f20-pipeline") deployed [wishlists](https://github.com/wishlists/wishlists/releases/tag/deploy-ibm-yp-us-south-ag7387-nyu.edu-dev-20201118-045327 "deploy-ibm-yp-us-south-ag7387-nyu.edu-dev-20201118-045327") to [dev](https://console.bluemix.net/apps/87d9b0cd-cdb0-4349-b181-099124ba4b73?env_id=ibm:yp:us-south "ibm:yp:us-south:ag7387@nyu.edu:dev"), including commit 520248baff0ed14f82783b368fbeffc52b364a46

**Comment by abhinavGupta16** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b7dd79b7-17cc-412e-98f1-e1a234aafd1c?env_id=ibm:yp:us-south "nyu-wishlist-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/76e35b85-cc07-4faf-b3ae-ee3dbe88d89f "nyu-wishlist-service-f20-pipeline") deployed [wishlists](https://github.com/wishlists/wishlists/releases/tag/deploy-ibm-yp-us-south-ag7387-nyu.edu-prod-20201118-045906 "deploy-ibm-yp-us-south-ag7387-nyu.edu-prod-20201118-045906") to [prod](https://console.bluemix.net/apps/b9e11a39-3222-4ca4-a89b-8f6a16a809d0?env_id=ibm:yp:us-south "ibm:yp:us-south:ag7387@nyu.edu:prod"), including commit 520248baff0ed14f82783b368fbeffc52b364a46

**Pull request merged**
