### PR TITLE
check and fix some pep8 and PyLint violations

### PR DESCRIPTION
**Pull request by sqz0914**
1. Fix some pep8 and PyLint violations. The score has reached the required 9/10.
2. Remove the data type check of the variable ``` name ``` in LIST API.
3. Update README.md file by adding ``` vagrant provision ``` to the prerequisites.

### CODE REVIEW

**Comment by abhinavGupta16** [comment]
Were you able to do any changes for pylint or no luck with that?

**Comment by sqz0914** [comment]
> Were you able to do any changes for pylint or no luck with that?

You mean disable some violation check?
I just disable some check and now both are 10/10.
Screen Shot 2020-10-17 at 7 43 37 PM

**Comment by abhinavGupta16** [comment]
> > Were you able to do any changes for pylint or no luck with that?
> 
> You mean disable some violation check?
> I just disable some check and now both are 10/10.
> Screen Shot 2020-10-17 at 7 43 37 PM

No no! We cannot disable any other checks apart from E1101

image


I meant to fix the errors. lol!

**Review by abhinavGupta16 — DISMISSED** [review]
Added in reply comment, regarding disable pylint

**Comment by sqz0914** [comment]
> > > Were you able to do any changes for pylint or no luck with that?
> > 
> > 
> > You mean disable some violation check?
> > I just disable some check and now both are 10/10.
> > Screen Shot 2020-10-17 at 7 43 37 PM
> 
> No no! We cannot disable any other checks apart from E1101
> 
> image
> 
> I meant to fix the errors. lol!

I add some Class or Method decorate strings, remove some real unused variables, and fix the dangerous empty list. But for the other violations, I think we don't have to fix them as they are not real issues I think. I have just removed the disables except E1101.

**Comment by sqz0914** [comment]
These changes have been done on another branch and have been merged to ``` master ```

**Pull request closed without merging**
