### PR TITLE
Add error handlers

### LINKED ISSUE #23: Add error handlers
**As a** developer  
**I need** the unified error handlers
**So that** we can override the default error handlers and ensure that only JSON message returned.

**Assumptions:** 
* Vagrant file and Skeleton Flask is set up

**Acceptance Criteria:**
```
Given - I have a created error handler
When I put a wrong request on web page
Then the error message will be returned in JSON format
```

### PR DESCRIPTION
**Pull request by Jesse1204**
Added error handlers in service.py
Code coverage:
image
Please note that I didn't write separate test cases for error handlers. I feel like it's more reasonable to include error handler test cases as part of each method's test cases. We should add it when we implement the methods which call error handlers.

### CODE REVIEW

**Review by abhinavGupta16 — CHANGES_REQUESTED** [review]
I believe service URLs are only required to check if that service is working properly.
All of the errors are universal for all the URLs for the microservice, and therefore need to be tested out separately. We would therefore need to add the test cases for error handlers separately. These are independent of any service that the microservice provides.

**Comment by sqz0914** [comment]
> I believe service URLs are only required to check if that service is working properly.
> All of the errors are universal for all the URLs for the microservice, and therefore need to be tested out separately. We would therefore need to add the test cases for error handlers separately. These are independent of any service that the microservice provides.

**Comment by sqz0914** [comment]
But the error handler will be triggered if we do some invalid actions on some routes which in this case will be some of our services. So I think it is service-related. The current method to solve this may be that we implement all the service first, write corresponding test cases, and then check the overall coverage. If the coverage does not achieve the homework requirement, we can open a new issue and input more test cases to cover more code.

**Comment by abhinavGupta16** [comment]
> But the error handler will be triggered if we do some invalid actions on some routes which in this case will be some of our services. So I think it is service-related. The current method to solve this may be that we implement all the service first, write corresponding test cases, and then check the overall coverage. If the coverage does not achieve the homework requirement, we can open a new issue and input more test cases to cover more code.

Then the question arises, who does it? because a 404 not found for example will be thrown for /wish or /wishlists/get or any other URL that does not exist. Irrespective of the URL, the error handlers should work. If they work for one, they work for every other URL as well. **The service does check for a DataValidation error or any other exception.** The job of the service is to throw the appropriate exception. After that, it's the job of the error handler to give the appropriate response for any exception, irrespective of the service or method throwing it. Therefore, error handlers are universal for all services, and therefore independent in my opinion. If the error handlers work properly, and the exceptions are tested in service, then I am assured that the response to the client is always appropriate.

Irrespectively, if we had travis-ci deployed, the PR would simply get rejected due to lesser coverage. How does one know the error handlers implemented in this PR work properly without the test case? What do you think?

**Review by sqz0914 — DISMISSED** [review]

**Comment by abhinavGupta16** [comment]
After much discussion, I believe we then add the test case for 500 and 415 and the rest should be written by each service.
Each end-point service should test for 404, 415, and 400. What do you think?

@Jesse1204 @sqz0914 @xiafanzeng @yf1357

**Comment by yf1357** [comment]
> After much discussion, I believe we then add the test case for 500 and 415 and the rest should be written by each service.
> Each end-point service should test for 404, 415, and 400. What do you think?
> 
> @Jesse1204 @sqz0914 @xiafanzeng @yf1357

Ok. But I think some api only requires test cases for 404, since no content-type needed.  Also, please check with " flake8 --count --max-complexity=10 --statistics service", there is "E501 line too long" error.

**Comment by abhinavGupta16** [comment]
> > After much discussion, I believe we then add the test case for 500 and 415 and the rest should be written by each service.
> > Each end-point service should test for 404, 415, and 400. What do you think?
> > @Jesse1204 @sqz0914 @xiafanzeng @yf1357
> 
> Ok. But I think some api only requires test cases for 404, since no content-type needed. Also, please check with " flake8 --count --max-complexity=10 --statistics service", there is "E501 line too long" error.

415 will be needed for APIs that use a json request (check if the request is json) and 400 is bad-request which is Data Validation Error

@Jesse1204 - Can we add the test cases for 500 and 415?

**Comment by sqz0914** [comment]
> > > After much discussion, I believe we then add the test case for 500 and 415 and the rest should be written by each service.
> > > Each end-point service should test for 404, 415, and 400. What do you think?
> > > @Jesse1204 @sqz0914 @xiafanzeng @yf1357
> > 
> > 
> > Ok. But I think some api only requires test cases for 404, since no content-type needed. Also, please check with " flake8 --count --max-complexity=10 --statistics service", there is "E501 line too long" error.
> 
> 415 will be needed for APIs that use a json request (check if the request is json) and 400 is bad-request which is Data Validation Error
> 
> @Jesse1204 - Can we add the test cases for 500 and 415?

I think Jesse may add test cases for 500 and 405? 415 will be tested in our services just as you mentioned. Or we can add 500 and 405 test cases at the very last through opening a new issue if no service test case cover these error handlers. I remember Professor mentioned yesterday that he usually leaves the error handler test cases for last.

**Comment by abhinavGupta16** [comment]
> > > > After much discussion, I believe we then add the test case for 500 and 415 and the rest should be written by each service.
> > > > Each end-point service should test for 404, 415, and 400. What do you think?
> > > > @Jesse1204 @sqz0914 @xiafanzeng @yf1357
> > > 
> > > 
> > > Ok. But I think some api only requires test cases for 404, since no content-type needed. Also, please check with " flake8 --count --max-complexity=10 --statistics service", there is "E501 line too long" error.
> > 
> > 
> > 415 will be needed for APIs that use a json request (check if the request is json) and 400 is bad-request which is Data Validation Error
> > @Jesse1204 - Can we add the test cases for 500 and 415?
> 
> I think Jesse may add test cases for 500 and 405? 415 will be tested in our services just as you mentioned. Or we can add 500 and 405 test cases at the very last through opening a new issue if no service test case cover these error handlers. I remember Professor mentioned yesterday that he usually leaves the error handler test cases for last.

Ohh sorry, that's my bad. I meant 500 and 405. Ideally, we shouldn't leave it to the end, in my opinion as it only requires 2 test cases. However, it's also holding 2 other PRs. So, now or later, it's the call of the Scrum Master I guess which in this case is @Jesse1204 .

**Comment by Jesse1204** [comment]
> > > > After much discussion, I believe we then add the test case for 500 and 415 and the rest should be written by each service.
> > > > Each end-point service should test for 404, 415, and 400. What do you think?
> > > > @Jesse1204 @sqz0914 @xiafanzeng @yf1357
> > > 
> > > 
> > > Ok. But I think some api only requires test cases for 404, since no content-type needed. Also, please check with " flake8 --count --max-complexity=10 --statistics service", there is "E501 line too long" error.
> > 
> > 
> > 415 will be needed for APIs that use a json request (check if the request is json) and 400 is bad-request which is Data Validation Error
> > @Jesse1204 - Can we add the test cases for 500 and 415?
> 
> I think Jesse may add test cases for 500 and 405? 415 will be tested in our services just as you mentioned. Or we can add 500 and 405 test cases at the very last through opening a new issue if no service test case cover these error handlers. I remember Professor mentioned yesterday that he usually leaves the error handler test cases for last.

Added 405 & 500 unit tests.

**Comment by abhinavGupta16** [comment]
@Jesse1204 - Changes look good. Merge the branch with master to resolve conflicts. The rest should be good.

**Review by sqz0914 — DISMISSED** [review]

**Review by abhinavGupta16 — APPROVED** [review]

**Comment by abhinavGupta16** [comment]
> @Jesse1204 - Changes look good. Merge the branch with master to resolve conflicts. The rest should be good.

resolved.

**Review by sqz0914 — APPROVED** [review]
Run the code and test cases locally and everything is good.

**Pull request merged**
