### PR TITLE
created models.py, tests_models.py and other config files

### LINKED ISSUE #12: Create a data model
**As a** Developer  
**I need** a data model  
**So that** I can hold my model definitions of my wishlist resources 

**Assumptions:** 
* We will be using Python
* We will use SQL Alchemy 

**Design:**
* The following methods need to be implemented
-- [ ] serialise()
-- [ ] deserialise()
-- [ ] dbinit()
* create a class wishlists with the following fields
-- id (primary_key)
-- wishlist_name
-- user_id (comes from user API)
-- items

* class should be called Item
* The following fields are needed
-- id (primary_key)
-- wishlist_id (foreign key)
-- product_id (comes from product API)
-- product_name (comes from product API)

**Acceptance Criteria:**

When I run ```python models.py```
Then I should setup all the model definitions of wishlist

### PR DESCRIPTION
**Pull request by abhinavGupta16**
Models.py - **coverage 99%**
models.py, tests_models.py follow **pep8 style**

created models.py, tests_models.py, .coveragerc, .dockerignore.

**Fixed setup.cfg**

### CODE REVIEW

**Comment by yf1357** [comment]
It works for me. Could you also update readme.md for testing part?

**Comment by yf1357** [comment]
Also remember to change "Pet" to "Wishlist" in models.py

**Comment by abhinavGupta16** [comment]
> It works for me. Could you also update readme.md for testing part?

Done

**Comment by abhinavGupta16** [comment]
> Also remember to change "Pet" to "Wishlist" in models.py

Good catch. Done!

**Review by yf1357 — APPROVED** [review]

**Review by sqz0914 — APPROVED** [review]

**Pull request merged**
