### PR TITLE
Create a skeleton Flask project

### LINKED ISSUE #5: Create a skeleton Flask project to seed repo
**As a** Developer  
**I need** some starter code  
**So that** I can start adding features and services

**Assumptions:** 
* We will be using Python with Flask
* Do not implement any CRUD methods

**Acceptance Criteria:**
When I issue a git clone on the project
I should get a minimal Flask application
When I run python server.py
I should have a Flask server running at localhost:5000

### PR DESCRIPTION
**Pull request by yf1357**

### CODE REVIEW

**Review by sqz0914 — DISMISSED** [review]
Can successfully visit http://localhost:5000/wishlists after running the code

**Review by abhinavGupta16 — CHANGES_REQUESTED** [review]
Needs test cases for service.py (error handlers). We need to maintain 95% coverage

We can be more descriptive on the README.md. I am not sure I follow line 8 for example.

**Comment by yf1357** [comment]
> Needs test cases for service.py (error handlers). We need to maintain 95% coverage
> 
> We can be more descriptive on the README.md. I am not sure I follow line 8 for example.

Test cases should be created after issue#13 Create unit tests skeleton files. The readme.md is updated and uses https://github.com/nyu-devops/lab-flask-rest for reference.

**Comment by abhinavGupta16** [comment]
> > Needs test cases for service.py (error handlers). We need to maintain 95% coverage
> > We can be more descriptive on the README.md. I am not sure I follow line 8 for example.
> 
> Test cases should be created after issue#13 Create unit tests skeleton files. The readme.md is updated and uses https://github.com/nyu-devops/lab-flask-rest for reference.

We then need to update #13 to add test cases for service.py it only suggests to create empty test files.

**Comment by yf1357** [comment]
> > > Needs test cases for service.py (error handlers). We need to maintain 95% coverage
> > > We can be more descriptive on the README.md. I am not sure I follow line 8 for example.
> > 
> > 
> > Test cases should be created after issue#13 Create unit tests skeleton files. The readme.md is updated and uses https://github.com/nyu-devops/lab-flask-rest for reference.
> 
> We then need to update #13 to add test cases for service.py it only suggests to create empty test files.

I removed error handlers part for matching this story requirement and easy understanding. We can add another new story for error message and its test cases rather than modify issue#13. Test cases should be created with functions. Please review current version and let me know if there is any problem.

**Review by abhinavGupta16 — APPROVED** [review]

**Review by sqz0914 — APPROVED** [review]

**Pull request merged**
