### PR TITLE
Add LIST items API 

### LINKED ISSUE #39: Add the service to LIST all items in my Wishlist
**As a** User
**I need** the ability to list all items in my wishlist
**So that** I can see all the existing items in my wishlist and may perform further actions on the items of my wishlists

**Assumptions:** 
User will pass the wishlist ID
* A call to ``` GET /wishlist/{id}/items ``` should list all wishlists

**Acceptance Criteria:**

When I call ``` GET /wishlists/{id}/items ```
I should see a list of all items in my wishlist as a JSON string

**Code Reference**
You can refer to https://github.com/nyu-devops/sample-accounts/blob/master/service/service.py#L211 for a sample implementation.

### PR DESCRIPTION
**Pull request by yf1357**
1. add list items function
2. add test_get_items_from_wishlist() and related error handling test case
image

### CODE REVIEW

**Comment by abhinavGupta16** [comment]
@yf1357 - Need to resolve conflicts with master, looks good otherwise

**Comment by yf1357** [comment]
@sqz0914 It seems "nosetests" fails after your modification. Could you check again or rollback to the previous version?

**Comment by yf1357** [comment]
> @sqz0914 It seems "nosetests" fails after your modification. Could you check again or rollback to the previous version?

image

**Comment by sqz0914** [comment]
> > @sqz0914 It seems "nosetests" fails after your modification. Could you check again or rollback to the previous version?
> 
> image

Sure, sorry for the confusion.

**Review by sqz0914 — APPROVED** [review]
The local Postman test is fine. Unit test cases pass successfully.
Screen Shot 2020-10-18 at 9 10 05 PM

**Review by abhinavGupta16 — APPROVED** [review]

**Pull request merged**
