### PR TITLE
Created test_service.py and test_model.py

### LINKED ISSUE #13: Create unit tests skeleton files
**As a** Developer  
**I need** to test our service and model  
**So that** we need to add the unit tests  

**Assumptions:** 
* setup an empty test file

**Acceptance Criteria:**
```
Created test_service.py and test_model.py
```

### PR DESCRIPTION
**Pull request by xiafanzeng**

### CODE REVIEW

**Comment by yf1357** [comment]
How about adding a "tests" folder and move both files in it? Just like https://github.com/nyu-devops/lab-flask-tdd

**Review by abhinavGupta16 — CHANGES_REQUESTED** [review]
The files should be in a Test directory. checkout labs-flask-tdd for reference

**Review by abhinavGupta16 — CHANGES_REQUESTED** [review]
nosetests does not work. Although, I am not 100% sure that it should. However, it throws compilation errors. You may have to check and modify the setup.cfg 

You may refer to lab-flask-tdd for details.

**Comment by abhinavGupta16** [comment]
Duplicate. Code already exists.

**Pull request closed without merging**
