### PR TITLE
Changes to Add and get items from a wishlist

### LINKED ISSUE #28: GET an item from an existing Wishlist
**As a** User
**I need** the ability to get one item from my wishlist
**So that** I can perform CRUD operations on the item of my wishlist

**Assumptions:** 
* The wishlist ID should be passed in by the user
* The item ID should be passed in by the user
* A call to ``` GET  /wishlists/{id}/items/{id} ``` should show the content of the desired item

**Acceptance Criteria:**

Given - I have a read API
When I call ``` GET  /wishlists/{id}/items/{id}  ```
I should see the item that I want to review for the given ids

### PR DESCRIPTION
**Pull request by abhinavGupta16**
1. Changes to add an item to a wishlist
2. Changes to get an item from a wishlist
3. Changes to models.py to remove code redundancy - (modeled after https://github.com/nyu-devops/sample-accounts/blob/master/service/models.py)
4. Changes to service._init__.py (now similar to labs-flask-tdd)
5. Changes to vagrant file to add test_db - **Please run vagrant provision**
6. Changes to test_service.py and test_models.py to use the test_db

nosetests - 
image

**Coverage at 99%, 100% for service.py and models.py**, yay!

### CODE REVIEW

**Review by sqz0914 — DISMISSED** [review]

**Review by sqz0914 — CHANGES_REQUESTED** [review]
Everything seems good to me. I also run provision and the tests pass successfully.
```5. Changes to vagrant file to add test_db - Please run vagrant provision```
But could you include this command in the README.md? If some others want to run nosetests by just following the current commands in the README.md, it will throw some error messages related to the database.

**Comment by abhinavGupta16** [comment]
> Everything seems good to me. I also run provision and the tests pass successfully.
> `5. Changes to vagrant file to add test_db - Please run vagrant provision`
> But could you include this command in the README.md? If some others want to run nosetests by just following the current commands in the README.md, it will throw some error messages related to the database.

Good point, but if someone does clone the code from readme.md, vagrant up should suffice. vagrant provision will be redundant.
Here, we need a vagrant provision only because we already have the box. It will be a one-time thing as the change is to setup the test db. Therefore, I did not add it to the readme as it is not required if you follow the steps mentioned there.

**Review by sqz0914 — DISMISSED** [review]

**Comment by sqz0914** [comment]
> > Everything seems good to me. I also run provision and the tests pass successfully.
> > `5. Changes to vagrant file to add test_db - Please run vagrant provision`
> > But could you include this command in the README.md? If some others want to run nosetests by just following the current commands in the README.md, it will throw some error messages related to the database.
> 
> Good point, but if someone does clone the code from readme.md, vagrant up should suffice. vagrant provision will be redundant.
> Here, we need a vagrant provision only because we already have the box. It will be a one-time thing as the change is to setup the test db. Therefore, I did not add it to the readme as it is not required if you follow the steps mentioned there.

But we cannot assume others would not have the same situation as we have? What if others have already had the box? I think it is necessary to mention it in the README.md so that in case the error appears, they don't need to google.

**Review by sqz0914 — CHANGES_REQUESTED** [review]
See my reply

**Comment by abhinavGupta16** [comment]
> See my reply

Done

**Review by sqz0914 — DISMISSED** [review]

**Comment by sqz0914** [comment]
> > See my reply
> 
> Done

Thanks!

**Review by yf1357 — CHANGES_REQUESTED** [review]
pep8 compliance in tests folder might be checked by "flake8 --count --max-complexity=10 --statistics tests".
image

**Comment by yf1357** [comment]
And for add_items_to_wishlist() function, we are allowed to add any wishlist_id. Do you think we should add some restrictions here?
image

**Comment by abhinavGupta16** [comment]
> And for add_items_to_wishlist() function, we are allowed to add any wishlist_id. Do you think we should add some restrictions here?
> image

That wishlist_id in the post request is not used. It is only added to the wishlist that the user passes in the URL. The problem is, if you don't pass the wishlist_id, the deserialization fails for items, which is a problem. I spoke to the professor asking that we should remove it from there, but then decided against that, as an item cannot exist without a wishlist. 

Maybe what we can do, is to put in a check if the wishlist id in the item and the URL are same, only then proceed. What do you think?

**Comment by yf1357** [comment]
> > And for add_items_to_wishlist() function, we are allowed to add any wishlist_id. Do you think we should add some restrictions here?
> > image
> 
> That wishlist_id in the post request is not used. It is only added to the wishlist that the user passes in the URL. The problem is, if you don't pass the wishlist_id, the deserialization fails for items, which is a problem. I spoke to the professor asking that we should remove it from there, but then decided against that, as an item cannot exist without a wishlist.
> 
> Maybe what we can do, is to put in a check if the wishlist id in the item and the URL are same, only then proceed. What do you think?

I agree. We cannot just move wishlist_id from items. It's ok to make a comparison, if different, then return "400 Bad Request" or modify it to the correct one.

**Comment by abhinavGupta16** [comment]
> > > And for add_items_to_wishlist() function, we are allowed to add any wishlist_id. Do you think we should add some restrictions here?
> > > image
> > 
> > 
> > That wishlist_id in the post request is not used. It is only added to the wishlist that the user passes in the URL. The problem is, if you don't pass the wishlist_id, the deserialization fails for items, which is a problem. I spoke to the professor asking that we should remove it from there, but then decided against that, as an item cannot exist without a wishlist.
> > Maybe what we can do, is to put in a check if the wishlist id in the item and the URL are same, only then proceed. What do you think?
> 
> I agree. We cannot just move wishlist_id from items. It's ok to make a comparison, if different, then return "400 Bad Request" or modify it to the correct one.

I added the check for bad request in case of wishlist_id mismatch with a test case.

**Review by yf1357 — APPROVED** [review]
image
image
Looks good.

**Review by sqz0914 — APPROVED** [review]

**Pull request merged**
