### PR TITLE
Feature abhinav #47 #71 restflaskplus swagger

### LINKED ISSUE #47: Refactor to use Flask-RESTPlus - /wishlists
**As a** developer 
**I need** to refactor application using Flask-RESTPlus
**So that**  I could provide Swagger documentation with very little effort

**Assumptions:** 
* We will use https://github.com/nyu-devops/lab-flask-restplus-swagger for reference.

**Acceptance Criteria:**
```
Given the application is refactored by Flask-RESTPlus
When a resource `/wishlists` is called `POST` and `GET`
Then The appropriate service method is executed
And test cases still work like the original
```

### LINKED ISSUE #71: Add Swagger Docs
**As a** developer  
**I need** to add Swagger annotations
**So that** we are able to document REST API using Flask-RESTPlus as shown in class  

**Assumptions:** 
* Ability to leverage Swagger support for Python
* Add Swagger configuration to services.py
* Annotate the code to support Swagger documentation generation
* Documentation endpoint should be at /api-docs URL

**Acceptance Criteria:**
```
Given I have the Swagger documentation set up
When I follow the `/api-docs` URL
Then I should get the documentation JSON in Swagger format
```

### PR DESCRIPTION
**Pull request by abhinavGupta16**

### CODE REVIEW

**Review by sqz0914 — DISMISSED** [review]

**Review by yf1357 — CHANGES_REQUESTED** [review]
The default json for post request results in 500 error
image
image
Changing id, wishlist_id, product_id to Integer works.

**Comment by abhinavGupta16** [comment]
> The default json for post request results in 500 error
> image
> image
> Changing id, wishlist_id, product_id to Integer works.

Changed them to Integer.

**Review by yf1357 — APPROVED** [review]

**Review by sqz0914 — APPROVED** [review]

**Comment by abhinavGupta16** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b7dd79b7-17cc-412e-98f1-e1a234aafd1c?env_id=ibm:yp:us-south "nyu-wishlist-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/76e35b85-cc07-4faf-b3ae-ee3dbe88d89f "nyu-wishlist-service-f20-pipeline") deployed [wishlists](https://github.com/wishlists/wishlists/releases/tag/deploy-ibm-yp-us-south-ag7387-nyu.edu-dev-20201124-021310 "deploy-ibm-yp-us-south-ag7387-nyu.edu-dev-20201124-021310") to [dev](https://console.bluemix.net/apps/87d9b0cd-cdb0-4349-b181-099124ba4b73?env_id=ibm:yp:us-south "ibm:yp:us-south:ag7387@nyu.edu:dev"), including commit ecdbacaad1e29c1d9a3058a6ee4a60612a11a147

**Comment by abhinavGupta16** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/b7dd79b7-17cc-412e-98f1-e1a234aafd1c?env_id=ibm:yp:us-south "nyu-wishlist-service-f20-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/76e35b85-cc07-4faf-b3ae-ee3dbe88d89f "nyu-wishlist-service-f20-pipeline") deployed [wishlists](https://github.com/wishlists/wishlists/releases/tag/deploy-ibm-yp-us-south-ag7387-nyu.edu-prod-20201124-203032 "deploy-ibm-yp-us-south-ag7387-nyu.edu-prod-20201124-203032") to [prod](https://console.bluemix.net/apps/b9e11a39-3222-4ca4-a89b-8f6a16a809d0?env_id=ibm:yp:us-south "ibm:yp:us-south:ag7387@nyu.edu:prod"), including commit ecdbacaad1e29c1d9a3058a6ee4a60612a11a147

**Pull request merged**
